version: "3.7"

volumes:
  warehouse_db:

services:
  warehouse-mongo:
    image: library/mongo:4.4.4
    container_name: warehouse-mongo
    restart: always
    network_mode: host
    volumes: 
      - warehouse_db:/data/db
  warehouse-mqtt:
    image: library/eclipse-mosquitto:2.0.14
    container_name: warehouse-mqtt
    restart: always
    network_mode: host
